version: '3.8'
services:
  app:
    build:
      context: .
      target: builder  # Usar estágio de builder para desenvolvimento
    ports:
      - "5005:5005"
    environment:
      - NODE_ENV=development
      - PORT=5005
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev  # Comando de desenvolvimento
    restart: unless-stopped