apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: production
  labels:
    app: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: {{DOCKERHUB_USERNAME}}/node-app:{{IMAGE_TAG}}
        ports:
        - containerPort: 5005
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5005"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5005
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5005
          initialDelaySeconds: 5
          periodSeconds: 5